# Generated by Django 4.2.6 on 2023-10-28 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_employee_latitude_remove_employee_longitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basicuser",
            old_name="latitude",
            new_name="contact_number",
        ),
        migrations.RenameField(
            model_name="basicuser",
            old_name="longitude",
            new_name="pno_number",
        ),
    ]
