# Generated by Django 4.2.6 on 2023-10-30 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_latitude_basicuser_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicuser",
            name="profile_pic",
            field=models.ImageField(default=None, upload_to="media/profile_pic"),
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_pic",
            field=models.ImageField(default=None, upload_to="media/profile_pic"),
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_number", models.CharField(default=None, max_length=100)),
                ("pno_number", models.CharField(default=None, max_length=100)),
                ("address", models.TextField()),
                ("gender", models.CharField(default=None, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_pic",
                    models.ImageField(default=None, upload_to="media/profile_pic"),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
