# Generated by Django 4.2.6 on 2023-10-30 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_basicuser_profile_pic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basicuser",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="users",
            name="profile_pic",
        ),
    ]
