# Generated by Django 4.2.6 on 2023-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_basicuser_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                default=None, null=True, upload_to="media/profile_pic"
            ),
        ),
    ]
