# Generated by Django 4.2.6 on 2023-10-30 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee",
            new_name="Superuser",
        ),
    ]
