# Generated by Django 4.2.6 on 2023-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicuser",
            name="profile_pic",
            field=models.ImageField(default="", upload_to="media/profile_pic"),
        ),
        migrations.AddField(
            model_name="superuser",
            name="profile_pic",
            field=models.ImageField(default="", upload_to="media/profile_pic"),
        ),
        migrations.AddField(
            model_name="users",
            name="profile_pic",
            field=models.ImageField(default="", upload_to="media/profile_pic"),
        ),
    ]
