# Generated by Django 4.2.6 on 2023-10-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_basicuser_profile_pic_superuser_profile_pic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basicuser",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="superuser",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="users",
            name="profile_pic",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.FileField(default="", upload_to="media/profile_pic"),
        ),
    ]
