# Generated by Django 4.2.6 on 2023-10-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'MASTERADMIN'), ('2', 'SUPERADMIN'), ('3', 'ADMIN'), ('4', 'USER')], default=1, max_length=50),
        ),
    ]
