# Generated by Django 4.2.4 on 2023-11-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_specialduty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialDuty',
        ),
    ]
