# Generated by Django 4.2.4 on 2023-11-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_delete_specialduty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_designation', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
    ]
